spring.application.name=Aurora
project.image = images/

spring.h2.console.enabled=true

spring.datasource.url = jdbc:h2:mem:test

spring.app.jwtSecret = mySecretKeyLDRW2004
spring.app.jwtExpirationMS = 300000